# Generated by Django 6.0.5 on 2026-06-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='root_path',
        ),
    ]
