# Generated by Django 6.0.5 on 2026-05-23 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blueprints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('relative_path', models.CharField()),
                ('ai_model', models.CharField(choices=[('gpt-image-1', 'Gpt Image 1')], max_length=100)),
                ('prompt', models.TextField()),
                ('device_type', models.CharField(choices=[('Phone', 'phone'), ('Desktop', 'desktop')])),
                ('accuracy_score', models.IntegerField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending')),
                ('generation_type', models.CharField(choices=[('initial', 'Initial'), ('re_prompt', 'Re-Prompt'), ('user_upload', 'User Upload')], default='initial', max_length=50)),
                ('review_note', models.TextField(blank=True)),
                ('upload_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blueprints.background')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blueprints.character')),
                ('previous_generation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_generation', to='images.image')),
                ('reference_images', models.ManyToManyField(blank=True, to='images.image')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blueprints.scene')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('background__isnull', True), ('character__isnull', False), ('scene__isnull', True)), models.Q(('background__isnull', False), ('character__isnull', True), ('scene__isnull', True)), models.Q(('background__isnull', True), ('character__isnull', True), ('scene__isnull', False)), _connector='OR'), name='image_belongs_to_exactly_one_owner'), models.CheckConstraint(condition=models.Q(('generation_type', 'user_upload'), ('upload_note__isnull', True), _connector='OR'), name='upload_note_required_when_user_uploads'), models.CheckConstraint(condition=models.Q(('generation_type', 'user_upload'), ('prompt__isnull', False), _connector='OR'), name='prompt_not_required_for_user_upload')],
            },
        ),
    ]
