# Generated by Django 6.0.5 on 2026-07-18 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0003_blueprint_created_at_blueprint_updated_at'),
        ('storyboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='blueprint',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='blueprints.blueprint'),
            preserve_default=False,
        ),
    ]
