# Generated by Django 6.0.5 on 2026-07-25 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0002_image_blueprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='previous_generation',
        ),
        migrations.AddField(
            model_name='image',
            name='parent_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='storyboards.image'),
        ),
    ]
