# Generated by Django 6.0.5 on 2026-07-25 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0004_imagestack'),
        ('storyboards', '0003_remove_image_previous_generation_image_parent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='background',
        ),
        migrations.RemoveField(
            model_name='image',
            name='blueprint',
        ),
        migrations.RemoveField(
            model_name='image',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='image',
            name='key',
        ),
        migrations.RemoveField(
            model_name='image',
            name='scene',
        ),
        migrations.AddField(
            model_name='image',
            name='image_stack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blueprints.imagestack'),
        ),
        migrations.AlterField(
            model_name='image',
            name='parent_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='storyboards.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='reference_images',
            field=models.ManyToManyField(blank=True, related_name='referenced_by', to='storyboards.image'),
        ),
    ]
