# Generated by Django 6.0.5 on 2026-05-23 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(default=dict)),
                ('generation_type', models.CharField(choices=[('initial', 'Initial'), ('re-prompt', 'Re-prompt')], default='initial', max_length=50)),
                ('review_status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('re_prompt', models.TextField(blank=True, max_length=500, null=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to='stories.story')),
            ],
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backgrounds', to='blueprints.blueprint')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('voice_id', models.TextField(blank=True, null=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='blueprints.blueprint')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('key', models.SlugField()),
                ('duration', models.IntegerField()),
                ('image_prompt', models.CharField(max_length=500)),
                ('video_prompt', models.CharField(max_length=500)),
                ('narration', models.TextField()),
                ('reference_image_keys', models.JSONField(default=list)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='blueprints.blueprint')),
            ],
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='blueprints.character')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='blueprints.scene')),
            ],
        ),
        migrations.AddConstraint(
            model_name='blueprint',
            constraint=models.UniqueConstraint(condition=models.Q(('review_status', 'accepted')), fields=('story',), name='unique_accepted_blueprint_per_story'),
        ),
        migrations.AddConstraint(
            model_name='blueprint',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('generation_type', 're-prompt'), _negated=True), ('re_prompt__isnull', False), _connector='OR'), name='re_prompt_required_for_re_prompt_type'),
        ),
    ]
