# Generated by Django 6.0.5 on 2026-06-18 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0002_rename_lines_dialogue_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blueprint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
