# Generated by Django 6.0.5 on 2026-07-25 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0003_blueprint_created_at_blueprint_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('characters', 'Characters'), ('backgrounds', 'Backgrounds'), ('scenes', 'Scenes')], max_length=23)),
                ('name', models.CharField(max_length=50)),
                ('background', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_stack', to='blueprints.background')),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_stacks', to='blueprints.blueprint')),
                ('characters', models.ManyToManyField(blank=True, related_name='image_stack', to='blueprints.character')),
                ('scene', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_stack', to='blueprints.scene')),
            ],
        ),
    ]
